#pragma config(Sensor, S1,     ATLAS,               sensorLowSpeed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//

void start_gyro(){
  ubyte I2Csnd[4];
  I2Csnd[0] = 3;    // Sending address, register, value.
  I2Csnd[1] = 0xD2; // I2C Address of gyro.
  ubyte I2Crec[1];        // We are looking for a single byte returned.

  //Write CTRL_REG1
  ////////////////////////////////////////////////////////////////////////////
    I2Csnd[2] = 0x20;      // Register address of CTRL_REG1
    I2Csnd[3] = 0x0F;      // Enable all axes. Disable power down.
    sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
    wait1Msec(10);
    readI2CReply(S1, I2Crec[0], 1);  // (Port 1, Reply Array, Bytes to Read)

  //Write CTRL_REG2
  ////////////////////////////////////////////////////////////////////////////
    I2Csnd[2] = 0x21;                  // Register address of CTRL_REG2
    I2Csnd[3] = 0x00;                  // No High Pass Filter
    sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
    wait1Msec(10);
    readI2CReply(S1, I2Crec[0], 1);   // (Port 1, Reply Array, Bytes to Read)

  //Write CTRL_REG3
  ////////////////////////////////////////////////////////////////////////////
    I2Csnd[2] = 0x22;      // Register address of CTRL_REG3
    I2Csnd[3] = 0x08;      // No interrupts.  Date ready.
    sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
    wait1Msec(10);
    readI2CReply(S1, I2Crec[0], 1);  // (Port 1, Reply Array, Bytes to Read)

  //Write CTRL_REG4
  ////////////////////////////////////////////////////////////////////////////
    I2Csnd[2] = 0x23;      // Register address of CTRL_REG4
    I2Csnd[3] = 0x30;      // Full scale range.
    sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
    wait1Msec(10);
    readI2CReply(S1, I2Crec[0], 1);  // (Port 1, Reply Array, Bytes to Read)

  //Write CTRL_REG5
  ////////////////////////////////////////////////////////////////////////////
    I2Csnd[2] = 0x24;      // Register address of CTRL_REG5
    I2Csnd[3] = 0x00;      // Enable all axes. Disable power down.
    sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
    wait1Msec(10);
    readI2CReply(S1, I2Crec[0], 1);  // (Port 1, Reply Array, Bytes to Read)
}

// Gyro: axis_reading gets a byte of axis reading data
ubyte gyro_axis_reading(ubyte reg){
  //ubyte ax = reg;
  ubyte I2Csnd[3];        //
  I2Csnd[0] = 2;    // Sending address, register.
  I2Csnd[1] = 0xD2; // I2C Address of gyro.
  I2Csnd[2] = reg;   // Register of the data we're requesting.

  ubyte I2Crec[1];        // We are looking for a single byte returned.

  sendI2CMsg(S1, I2Csnd[0], 1);     // (Port 1, Message Array, Reply Size)
  wait1Msec(10);
  readI2CReply(S1, I2Crec[0], 1);  // (Port 1, Reply Array, Bytes to Read)

  ubyte result = I2Crec[0];
  return result;
}


task main(){
  start_gyro();      // Fire up the gyro.  Initialize it.             Only needs to be done once.
  long x_val, y_val, z_val;      // Our assembled values.

  const string sFileName = "Spin.txt";  // Our destination KML File
  TFileIOResult nIoResult;
  TFileHandle hFileHandle;
  int nFileSize = 55000;
  hFileHandle = 0;
  Delete(sFileName, nIoResult);
  OpenWrite(hFileHandle, nIoResult, sFileName, nFileSize);

  while (true){

      // GYROSCOPE
      // Get x axis data.
      ubyte x_hb = gyro_axis_reading(0x29);
      ubyte x_lb = gyro_axis_reading(0x28);
      // Get y axis data.
      ubyte y_hb = gyro_axis_reading(0x2B);
      ubyte y_lb = gyro_axis_reading(0x2A);
      // Get z axis data.
      ubyte z_hb = gyro_axis_reading(0x2D);
      ubyte z_lb = gyro_axis_reading(0x2C);

      // Compute out the values.
      x_val = (x_lb+((long)(x_hb<<8)))/100;
      y_val = (y_lb+((long)(y_hb<<8)))/100;
      z_val = (z_lb+((long)(z_hb<<8)))/100;

      nxtDisplayTextLine(5, "%i", x_val);
      nxtDisplayTextLine(6, "%i", y_val);
      nxtDisplayTextLine(7, "%i", z_val);

      string str_x_val = (string)x_val;
      string str_y_val = (string)y_val;
      string str_z_val = (string)z_val;

      string write_coords = " ";
      strcat(write_coords, str_x_val);
      strcat(write_coords,", ");
      strcat(write_coords, str_y_val);
      strcat(write_coords, ", ");
      strcat(write_coords, str_z_val);
      strcat(write_coords, "\r\n");

      WriteString(hFileHandle, nIoResult, write_coords);
    wait1Msec(5);
  }
}
